@ECHO OFF & SETLOCAL ENABLEEXTENSIONS DISABLEDELAYEDEXPANSION
PUSHD %~dp0

SET "VARIANT=%~1"
IF [%VARIANT%] == [] SET "VARIANT=deb"


CMD /C makmake Paperclip wins
nmake /NOLOGO /S /F PAPERCLIP.WINS %VARIANT%

REM # return the errorlevel of NMAKE,
REM # instead of the POPD
REM #
POPD & EXIT /B %ERRORLEVEL%
